### ISSUE TITLE
Not able to load example json from http://fmpp.sourceforge.net/dataloader.html#key_json

### ISSUE THREAD

**Issue by firen** [freemarker/fmpp#14]
When I try to load json from http://fmpp.sourceforge.net/dataloader.html#key_json I get following error:
```
[ERROR] Failed to execute goal com.googlecode.fmpp-maven-plugin:fmpp-maven-plugin:1.1:generate (generate-mailboxes) on project mailboxes-configuration: Failed to apply the value of the "data" setting.
[ERROR] 
[ERROR] Caused by:
[ERROR] TDD error: Function doesn't evalute to a Map, but to fmpp.models.JSONArrayNode, so it can't be merged into the hash.
[ERROR] Error location: line 1, column 1:
[ERROR] json(../data/mailboxes-data.txt, UTF-8)
[ERROR] ^
```
Can anyone try to reproduce it?

**Comment by ddekany** [comment]
Isn't it true what the error message says? I guess you have an array in that JSON, and then in TDD you try to merge it in instead of giving a name to it.

**Comment by firen** [comment]
I have fixed the problem by adding label **conf** to json function.
data = **conf**:json(../target/fmpp/mailboxes-data-dev.json, UTF-8)

**Comment by ddekany** [comment]
I have updated the documentation of `json` to address this kind of problem.

**Comment by firen** [comment]
Great. Thx.

**Comment by citizentim** [comment]
Why should this not work?  If it can be merged in from TDD, for instance, why does JSON require a label?  

The documentation says "If a JSON file defines a JSON object instead (like { "applicants": [ ... ], "otherStuff": ... }), then, if you omit the label, the top-level name-value pairs from the JSON object will be added to the data-model directly." 

This seems like a bug to me.

**Comment by citizentim** [comment]
If it is because it is an object with an anonymous root, then shouldn't all values within the first level of the object be added to the root of the hash directly?

**Comment by ddekany** [comment]
This issue is about adding a JSON *array* to the root hash without name (or "label", as you have put it). Adding a JSON object to it without name should work (and I hope it does too).

**Comment by citizentim** [comment]
That's what I'm saying - a JSON object will not load without first giving it a name - it gives an error about merging into the map (my instance is offline at the moment but can produce the exact error sometime today or tomorrow).  I'm using 0.9.15.  I can send you a JSON file and template offline to test with.  I'd also be happy to open a new bug, if you'd like.
