### ISSUE TITLE
Typos in FMPP docs

### ISSUE THREAD

**Issue by edendramis** [freemarker/fmpp#15]
http://fmpp.sourceforge.net/dataloader.html#key_antProperites

`properyName1`, `properyName2`, `properyNameN` should be spelled "property"

Also this phrase (emphasis mine):

Parameters that refer to **not existing** Ant properties will be silently ignored

Should be:

Parameters that refer to **non-existing** Ant properties will be silently ignored

**Comment by ddekany** [comment]
Thanks, fixed on Git.
