### ISSUE TITLE
Upgrade to freemarker 2.3.25?

### ISSUE THREAD

**Issue by corydolphin** [freemarker/fmpp#19]
Is it possible to update this to the most recent version of freemarker? 

I tried to build the project locally, so I could submit a diff, but could not get my environment setup.

Thanks,
Cory

**Comment by ddekany** [comment]
No no building is needed for that. Simply replace `freemarker.jar` with the latest one. See: http://fmpp.sourceforge.net/installing.html#updatingFreeMarker

Of course, if I ever get to creating a new release, it will contain that latest FreeMarker.

**Comment by ddekany** [comment]
FMPP 0.9.16 comes with Apache FreeMarker 2.3.28
