### ISSUE TITLE
Datamodel wrongly inserted with squareBracket

### ISSUE THREAD

**Issue by gorfo66** [freemarker/fmpp#25]
The templates i'm working on are written with square brackets.
In the configuration, I'm therefore configuring fmpp to use square brackets using this configuration item

tagSyntax : "squareBracket"

The template is correctly interpreted and converted.
The problem is when I want to inject datamodel using tdd file.
In such a case, the datamodel is inserted in the ftl template using <#assign> directives, with angle brackets, and the data is not interpreted as good freemarker directive.

**My template**
```
[#assign myDirective = 'title' /]
<h1>${myDirective}</h1>
```

**Data model**
```
dataObject = {
  "key1" : "string value"
};
```

**Result**
```
<#assign key1 = "string value"/>
<h1>title</h1>
```

**Comment by ddekany** [comment]
Sorry, I don't follow. How did that `<#assign ...>` get into the output?

**Comment by gorfo66** [comment]
Indeed, after deeper investigation the problem does not come from fmpp but from the wrapper i'm using on top which is strangely not using the fmpp data injection mechanism.

Sorry for that.
