### ISSUE TITLE
JSON data null does not get loaded as null but as JSONNode

### ISSUE THREAD

**Issue by FrEaKmAn** [freemarker/fmpp#27]
For the following FM file

```ftl
<#if value??>
    not null
<#else>
    is null
</#if>
```

I'm trying to render it using JSON data `{"value": null}`. My config is following

```
data: {"value":null}
```
When I run the command

`$ ./fmpp test.ftl -C config -o output`

the output is `not null`. Checking the code, I believe null gets wrapped to JSONNullNode (https://github.com/freemarker/fmpp/blob/master/src/main/java/fmpp/models/JSONNode.java#L89) as `value?is_node` returns true. If I test the same code directly in freemarker (using https://try.freemarker.apache.org/) it gets evaluated to `is null`.

Is this a bug or expected behaviour? Should I load JSON differently?

**Comment by ddekany** [comment]
As confusing as it is today, the config file is not JSON. (JSON wasn't a widely known thing yet when this was made.) The config file syntax is similar to typical legacy config file formats, in that quoting string values is optional, unless you have some special character in the value. So `{"value": null}` is the same as `{"value": "null"}`, or as `{value: null}`. And it doesn't have the concept of null either. You just omit the whole entry instead.

So, use a separate real json file, and the `json` data-loader. See: http://fmpp.sourceforge.net/dataloader.html#key_json

**Comment by FrEaKmAn** [comment]
Yes, everything works fine with json data-loader. Thank you.
